/**
 * Created by CDCT on 2017/10/12.
 */
var yinhui=[
        {"name":"妇幼保健","userLevel":"1",list:[
           {
               "name":"通用模态框","userLevel":"2",list:[],url:"page/通用模态框/通用对话框.html",icon:"image/icon/A1.png--image/icon/A1.png"
           },
           {
               "name":"2-1-1妇女基本信息","userLevel":"2",list:[],url:"page/妇女保健/2-1-1妇女基本信息登记表.html",icon:"image/icon/A1.png--image/icon/A1.png"
           },
           {
               "name":"2-2-2乳腺癌筛查登记表","userLevel":"2",list:[],url:"page/妇女保健/2-2-2乳腺癌筛查登记表.html",icon:"image/icon/A1.png--image/icon/A1.png"
           },
           {
               "name":"2-3-2宫颈癌筛查登记表","userLevel":"2",list:[],url:"page/妇女保健/2-3-2宫颈癌筛查登记表.html",icon:"image/icon/A1.png--image/icon/A1.png"
           },
           {
               "name":"2-4-2婚前医学检查登记表","userLevel":"2",list:[],url:"page/妇女保健/2-4-2婚前医学检查登记表.html",icon:"image/icon/A1.png--image/icon/A1.png"
           },
           {
               "name":"2-6-2叶酸发放登记表","userLevel":"2",list:[],url:"page/妇女保健/2-6-2叶酸发放登记表.html",icon:"image/icon/A1.png--image/icon/A1.png"
           },
           {
               "name":"通用顶部","userLevel":"2",list:[],url:"page/妇女保健/tabCom.html",icon:"image/icon/A1.png--image/icon/A1.png"
           },
           {
               "name":"表格一","userLevel":"2",list:[],url:"page/妇女保健/表格一.html",icon:"image/icon/A1.png--image/icon/A1.png"
           },
           {
               "name":"表格二","userLevel":"2",list:[],url:"page/妇女保健/表格二.html",icon:"image/icon/A1.png--image/icon/A1.png"
           },
           {
               "name":"表格三","userLevel":"2",list:[],url:"page/妇女保健/表格三.html",icon:"image/icon/A1.png--image/icon/A1.png"
           },
           {
               "name":"表格四","userLevel":"2",list:[],url:"page/妇女保健/表格四.html",icon:"image/icon/A1.png--image/icon/A1.png"
           },
           {
               "name":"通用按钮","userLevel":"2",list:[],url:"page/妇女保健/通用按钮.html",icon:"image/icon/A1.png--image/icon/A1.png"
           }
        ],icon:"image/icon/A1.png--image/icon/A1.png"},
        {"name":"孕产妇保健","userLevel":"1",list:[
            {
                "name":"孕产妇保健tab","userLevel":"2",list:[],url:"page/孕产妇保健/multiNav.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"产前检查复诊服务记录表","userLevel":"2",list:[],url:"page/孕产妇保健/产前检查复诊服务记录表.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"产前随访","userLevel":"2",list:[],url:"page/孕产妇保健/产前随访.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"产后访视记录表","userLevel":"2",list:[],url:"page/孕产妇保健/产后访视记录表.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"叶酸增补","userLevel":"2",list:[],url:"page/孕产妇保健/叶酸增补.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"孕产妇基本信息登记表","userLevel":"2",list:[],url:"page/孕产妇保健/孕产妇基本信息登记表.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"居民死亡医学证明书","userLevel":"2",list:[],url:"page/孕产妇保健/居民死亡医学证明书.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"工作台","userLevel":"2",list:[],url:"page/孕产妇保健/工作台.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"新增分娩记录","userLevel":"2",list:[],url:"page/孕产妇保健/新增分娩记录.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"梅毒感染孕妇登记","userLevel":"2",list:[],url:"page/孕产妇保健/梅毒感染孕妇登记.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"梅毒感染孕妇随访登记","userLevel":"2",list:[],url:"page/孕产妇保健/梅毒感染孕妇随访登记.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"艾滋病感染孕产妇妊娠登记","userLevel":"2",list:[],url:"page/孕产妇保健/艾滋病感染孕产妇妊娠登记.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"艾滋病感染孕妇登记","userLevel":"2",list:[],url:"page/孕产妇保健/艾滋病感染孕妇登记.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"高危妊娠评分表","userLevel":"2",list:[],url:"page/孕产妇保健/高危妊娠评分表.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"高危筛查登记表","userLevel":"2",list:[],url:"page/孕产妇保健/高危筛查登记表.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"第n次产前服务记录表","userLevel":"2",list:[],url:"page/孕产妇保健/第n次产前服务记录表.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"产后42天健康检查记录表","userLevel":"2",list:[],url:"page/孕产妇保健/产后42天健康检查记录表.html",icon:"image/icon/A1.png--image/icon/A1.png"
            }
        ],icon:"image/icon/A1.png--image/icon/A1.png"},
        {"name":"儿童保健","userLevel":"1",list:[
            {
                "name":"体弱儿童专项","userLevel":"2",list:[],url:"page/儿童保健/体弱儿童专项.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"体弱儿童随访","userLevel":"2",list:[],url:"page/儿童保健/体弱儿童随访.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"儿童基本信息登记表","userLevel":"2",list:[],url:"page/儿童保健/儿童基本信息登记表.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"儿童档案Tab","userLevel":"2",list:[],url:"page/儿童保健/儿童档案Tab.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"出生医学证明登记","userLevel":"2",list:[],url:"page/儿童保健/出生医学证明登记.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"小儿佝偻病防治登记","userLevel":"2",list:[],url:"page/儿童保健/小儿佝偻病防治登记.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"小儿佝偻病防治随访","userLevel":"2",list:[],url:"page/儿童保健/小儿佝偻病防治随访.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"小儿肺炎防治记录","userLevel":"2",list:[],url:"page/儿童保健/小儿肺炎防治记录.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"小儿腹泻防治记录","userLevel":"2",list:[],url:"page/儿童保健/小儿腹泻防治记录.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"小儿贫血防治专项登记","userLevel":"2",list:[],url:"page/儿童保健/小儿贫血防治专项登记.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"小儿贫血防治随访","userLevel":"2",list:[],url:"page/儿童保健/小儿贫血防治随访.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"新生儿听力筛查","userLevel":"2",list:[],url:"page/儿童保健/新生儿听力筛查.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"新生儿家庭访视记录表","userLevel":"2",list:[],url:"page/儿童保健/新生儿家庭访视记录表.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"新生儿疾病筛查","userLevel":"2",list:[],url:"page/儿童保健/新生儿疾病筛查.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"新生儿视力筛查","userLevel":"2",list:[],url:"page/儿童保健/新生儿视力筛查.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"梅毒感染新生儿登记","userLevel":"2",list:[],url:"page/儿童保健/梅毒感染新生儿登记.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"满月龄儿童健康检查记录表","userLevel":"2",list:[],url:"page/儿童保健/满月龄儿童健康检查记录表.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"缺陷儿童登记","userLevel":"2",list:[],url:"page/儿童保健/缺陷儿童登记.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"艾滋病病毒感染儿童专项","userLevel":"2",list:[],url:"page/儿童保健/艾滋病病毒感染儿童专项.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"艾滋病病毒感染儿童随访","userLevel":"2",list:[],url:"page/儿童保健/艾滋病病毒感染儿童随访.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"阿氏评分登记","userLevel":"2",list:[],url:"page/儿童保健/阿氏评分登记.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"预防接种卡","userLevel":"2",list:[],url:"page/儿童保健/预防接种卡.html",icon:"image/icon/A1.png--image/icon/A1.png"
            },
            {
                "name":"预防接种记录","userLevel":"2",list:[],url:"page/儿童保健/预防接种记录.html",icon:"image/icon/A1.png--image/icon/A1.png"
            }
        ],icon:"image/icon/A1.png--image/icon/A1.png"},
       {"name":"工作台","userLevel":"1",list:[],url:"page/孕产妇保健/工作台.html",icon:"image/icon/A1.png--image/icon/A1.png"},
       {"name":"新增页面","userLevel":"1",list:[ 
           {"name":"健康信息卡","userLevel":"2",list:[],url:"page/新建页面/健康信息卡.html",icon:"image/icon/A1.png--image/icon/A1.png"},
           {"name":"居民健康档案","userLevel":"2",list:[],url:"page/新建页面/居民健康档案.html",icon:"image/icon/A1.png--image/icon/A1.png"},
           {"name":"学生营养状况汇总表","userLevel":"2",list:[],url:"page/新建页面/学生营养状况汇总表.html",icon:"image/icon/A1.png--image/icon/A1.png"},
           {"name":"学生形态机能汇总表","userLevel":"2",list:[],url:"page/新建页面/学生形态机能汇总表.html",icon:"image/icon/A1.png--image/icon/A1.png"},
           {"name":"学生近视状况汇总表","userLevel":"2",list:[],url:"page/新建页面/学生近视状况汇总表.html",icon:"image/icon/A1.png--image/icon/A1.png"},
           {"name":"学生龋齿情况汇总表","userLevel":"2",list:[],url:"page/新建页面/学生龋齿情况汇总表.html",icon:"image/icon/A1.png--image/icon/A1.png"},
           {"name":"学生营养状况汇总表_table","userLevel":"2",list:[],url:"page/新建页面/学生营养状况汇总表_table.html",icon:"image/icon/A1.png--image/icon/A1.png"},
           {"name":"学生近视状况汇总表_table","userLevel":"2",list:[],url:"page/新建页面/学生近视状况汇总表_table.html",icon:"image/icon/A1.png--image/icon/A1.png"},
           {"name":"学生形态机能汇总表_table","userLevel":"2",list:[],url:"page/新建页面/学生形态机能汇总表_table.html",icon:"image/icon/A1.png--image/icon/A1.png"},
           {"name":"学生龋齿情况汇总表_table","userLevel":"2",list:[],url:"page/新建页面/学生龋齿情况汇总表_table.html",icon:"image/icon/A1.png--image/icon/A1.png"},
           {"name":"中小学生健康体检基础数据统计表","userLevel":"2",list:[],url:"page/新建页面/中小学生健康体检基础数据统计表.html",icon:"image/icon/A1.png--image/icon/A1.png"},
           {"name":"卫生计生监督协管信息巡查登记表","userLevel":"2",list:[],url:"page/新建页面/卫生计生监督协管信息巡查登记表.html",icon:"image/icon/A1.png--image/icon/A1.png"},
           {"name":"卫生计生监督协管信息报告登记表","userLevel":"2",list:[],url:"page/新建页面/卫生计生监督协管信息报告登记表.html",icon:"image/icon/A1.png--image/icon/A1.png"},
           
           {"name":"突发公共卫生事件相关信息报告卡","userLevel":"2",list:[],url:"page/新建页面/突发公共卫生事件相关信息报告卡.html",icon:"image/icon/A1.png--image/icon/A1.png"}
        ],icon:"image/icon/A1.png--image/icon/A1.png"},
];